# Generated by Django 4.2.3 on 2023-07-12 21:21

import ParkItWebApp.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[ParkItWebApp.accounts.validators.phone_number_validator]),
        ),
    ]
