# Generated by Django 4.2.3 on 2023-07-15 10:31

import ParkItWebApp.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[ParkItWebApp.accounts.validators.phone_number_validator, django.core.validators.MinLengthValidator(10)]),
        ),
    ]
