# Generated by Django 4.2.3 on 2023-07-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('VERY_POOR', 1), ('POOR', 2), ('GOOD', 3), ('VERY_GOOD', 4), ('EXCELLENT', 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_spots.parkingspot')),
            ],
        ),
    ]
