# Generated by Django 4.2.3 on 2023-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_parking_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, 'VERY_POOR'), (2, 'POOR'), (3, 'GOOD'), (4, 'VERY_GOOD'), (5, 'EXCELLENT')]),
        ),
    ]
