# Generated by Django 4.2.3 on 2023-07-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('VERY_POOR', 1), ('POOR', 2), ('GOOD', 3), ('VERY_GOOD', 4), ('EXCELLENT', 5)]),
        ),
    ]
