# Generated by Django 4.2.3 on 2023-07-07 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('post_code', models.CharField(validators=[django.core.validators.RegexValidator(message='Enter a valid Bulgarian postal code.', regex='^\\d{4}$')])),
                ('street', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('house_number', models.CharField(max_length=10)),
                ('type_of_space', models.CharField(choices=[('DRIVEWAY', 'Driveway'), ('CAR_PARK', 'Car Park'), ('GARAGE', 'Garage')])),
                ('spaces_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('electric_vehicle_charger', models.BooleanField()),
                ('hourly_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.BooleanField(choices=[(True, 'Available'), (False, 'Unavailable')])),
                ('image', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
