# Generated by Django 4.2.3 on 2023-07-18 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking_spots', '0002_alter_parkingspot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
