# Generated by Django 4.2.3 on 2023-07-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spots', '0003_alter_parkingspot_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='spaces_available',
        ),
    ]
